<a href="https://colab.research.google.com/github/IThanasis/ml/blob/main/example1_Nebosja_OLS_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sklearn.datasets import load_diabetes

In [2]:
X, y = load_diabetes(return_X_y=True)

In [3]:
X

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]])

In [4]:
y

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [5]:
X.shape

(442, 10)

In [7]:
len(y)

442

In [ ]:
# we will use only one feature
X = X[:,[2]]

In [13]:
X

array([[ 0.06169621],
       [-0.05147406],
       [ 0.04445121],
       [-0.01159501],
       [-0.03638469],
       [-0.04069594],
       [-0.04716281],
       [-0.00189471],
       [ 0.06169621],
       [ 0.03906215],
       [-0.08380842],
       [ 0.01750591],
       [-0.02884001],
       [-0.00189471],
       [-0.02560657],
       [-0.01806189],
       [ 0.04229559],
       [ 0.01211685],
       [-0.0105172 ],
       [-0.01806189],
       [-0.05686312],
       [-0.02237314],
       [-0.00405033],
       [ 0.06061839],
       [ 0.03582872],
       [-0.01267283],
       [-0.07734155],
       [ 0.05954058],
       [-0.02129532],
       [-0.00620595],
       [ 0.04445121],
       [-0.06548562],
       [ 0.12528712],
       [-0.05039625],
       [-0.06332999],
       [-0.03099563],
       [ 0.02289497],
       [ 0.01103904],
       [ 0.07139652],
       [ 0.01427248],
       [-0.00836158],
       [-0.06764124],
       [-0.0105172 ],
       [-0.02345095],
       [ 0.06816308],
       [-0

In [14]:
X.shape

(442, 1)

In [15]:
y.shape

(442,)

In [22]:
# training  (import training test split)
from sklearn.model_selection import train_test_split

In [27]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=False)

In [28]:
X_train.shape

(353, 1)

In [29]:
y_test.shape

(89,)

In [30]:
X_test.shape

(89, 1)

In [31]:
# apply linear regression
from sklearn.linear_model import  LinearRegression
# object = class
regressor = LinearRegression().fit(X_train, y_train)

In [32]:
regressor.coef_

array([957.76202681])

In [33]:
regressor.fit_intercept

True

In [34]:
regressor.intercept_

152.05351614434244

In [ ]:
# write our model
# y = 152.05351614434244 + 957.76202681*x

In [41]:
# evaluate our model (metrics: mse, rmse, r2)
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error

In [36]:
y_pred = regressor.predict(X_test)

In [37]:
y_pred

array([ 98.62446502, 195.6594878 , 143.0128265 , 120.30250202,
       199.78863771,  70.75270316, 157.46485117, 171.91687584,
       145.07740146, 252.435299  , 128.56080183, 146.10968893,
       115.14106464, 283.40392329, 315.40483506, 154.36798874,
       188.43347547,  96.55989007, 143.0128265 , 129.59308931,
       141.98053903, 119.27021455, 149.20655136, 217.3375248 ,
       161.59400108, 154.36798874, 115.14106464, 177.07831322,
        66.62355325, 210.11151247, 124.43165193, 123.39936445,
       133.72223922, 113.07648969, 166.75543846, 128.56080183,
       153.33570127, 218.36981228,  85.20472783, 123.39936445,
       107.91505231, 169.85230089, 153.33570127, 122.36707698,
       148.17426389, 166.75543846, 173.9814508 , 195.6594878 ,
       108.94733978, 120.30250202, 245.20928667, 203.91778761,
       269.9841861 ,  74.88185306, 241.08013676, 103.7859024 ,
       140.94825155, 125.4639394 , 208.04693752, 233.85412443,
       151.27112631, 158.49713865, 160.5617136 , 228.69

In [44]:
# import numpy as np
import numpy as np

In [47]:
print(f'Mean squared error: {mean_squared_error(y_test, y_pred):.2f}')
print(f'Coefficient of determination: {r2_score(y_test, y_pred):.2f}')
print(f'Mean absolute error: {mean_absolute_error(y_test, y_pred):.2f}')
print(f'Root mean squared error: {np.sqrt(mean_squared_error(y_test, y_pred)):.2f}')

Mean squared error: 4079.82
Coefficient of determination: 0.36
Mean absolute error: 53.79
Root mean squared error: 63.87


In [ ]:
# 1 - import our dataset
# from sklearn.datasets import load_diabetes
# X, y = load_diabetes(return_X_y=True)

# 2 - preprocess
# we will use only one feature -----X = X[:,[2]]

# 3 - traing our model
# training  ---from sklearn.model_selection import train_test_split
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=False)

# 4 - apply linear regression
# from sklearn.linear_model import  LinearRegression
# regressor = LinearRegression().fit(X_train, y_train)
# regressor.coef_    /    regressor.intercept_

# 5 - write our model  ------ y = 152.05351614434244 + 957.76202681*x

# 6 - evaluate our model (metrics: mse, rmse, r2) --------from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error